image: Visual Studio 2017
configuration: Release

environment:
  matrix:
    - BUILD_TYPE: tiny
    - BUILD_TYPE: regular-asm
    - BUILD_TYPE: regular32-asm

matrix:
  fast_finish: true

build_script:
 - git submodule update --init --recursive
 - Make.bat %BUILD_TYPE%
 - Make.bat

test_script:
 - Make.bat test

artifacts:
 - path: luvi.exe

