image: Visual Studio 2017
configuration: Release

environment:
  matrix:
    - BUILD_TYPE: tiny
    - BUILD_TYPE: tiny32
    - BUILD_TYPE: regular-asm
    - BUILD_TYPE: regular32-asm

matrix:
  fast_finish: true

install:
  - choco install nasm
  - set PATH="C:\Program Files\NASM";%PATH%

build_script:
 - git submodule update --init --recursive
 - Make.bat %BUILD_TYPE%
 - Make.bat

test_script:
 - Make.bat test

after_build:
 - Make.bat artifacts-%BUILD_TYPE%

artifacts:
 - path: artifacts\*.exe
 - path: artifacts\*.lib

cache:
  - C:\ProgramData\chocolatey\bin -> appveyor.yml
  - C:\ProgramData\chocolatey\lib -> appveyor.yml
  - C:\Program Files\NASM -> appveyor.yml

deploy:
  description: '' # appveyor says this is mandatory
  provider: GitHub
  auth_token:
    secure: bTslNShNLTsJrZ1cOoWU6gzI4boK7gveIkOzqn7SMwAyHOpb1HkemYgTvfZK2VRI
  artifact: /.*/ # everything
  draft: false
  prerelease: false
  force_update: true
  on:
    APPVEYOR_REPO_TAG: true # tags only
