configuration: Release

environment:
  matrix:
    - BUILD_TYPE: tiny
    - BUILD_TYPE: static

matrix:
  fast_finish: true

build_script:
 - git submodule update --init --recursive
 - Make.bat %BUILD_TYPE%
 - Make.bat

test_script:
 - Make.bat test

artifacts:
 - path: luvi.exe

notifications:
  email: true
  irc: "irc.freenode.org#luvit"
